StockMarketApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('backend.urls')),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/urls.py
from django.urls import path
from backend import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('stock_graph/', views.StockGraphView.as_view(), name='stock_graph'),
    path('dashboard/<str:stock_name>/', views.DashboardView.as_view(), name='dashboard'),
    path('watchlist/', views.WatchlistView.as_view(), name='watchlist'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
]

backend/models.py
from datetime import datetime

from dateutil.relativedelta import relativedelta
from django.db import models, transaction
import yfinance as yf
from django.contrib.auth.models import User


class Stock(models.Model):
    stock_name = models.CharField(max_length=10)
    date = models.DateField()
    open_price = models.FloatField()
    highest_price = models.FloatField()
    lowest_price = models.FloatField()
    close_price = models.FloatField()
    volume = models.FloatField()
    dividends = models.FloatField()
    stock_splits = models.FloatField()

    @classmethod
    @transaction.atomic
    def get_stock_info(cls, stock_name):
        end_date = datetime.today().strftime('%Y-%m-%d')
        start_date = (datetime.today() - relativedelta(years=5)).strftime('%Y-%m-%d')
        tickerData = yf.Ticker(stock_name)
        tickerDf = tickerData.history(period='1d', start=start_date, end=end_date)

        if tickerDf.empty:
            raise ValueError(f"No data found for stock: {stock_name}")

        new_stocks = []
        for index, row in tickerDf.iterrows():
            if not cls.objects.filter(stock_name=stock_name, date=index).exists():
                new_stock = cls(
                    stock_name=stock_name,
                    date=index,
                    open_price=row['Open'],
                    highest_price=row['High'],
                    lowest_price=row['Low'],
                    close_price=row['Close'],
                    volume=row['Volume'],
                    dividends=row['Dividends'],
                    stock_splits=row['Stock Splits']
                )
                new_stocks.append(new_stock)

        cls.objects.bulk_create(new_stocks)

    @classmethod
    def get_data(cls, stock_name):
        stock_name = stock_name.upper()
        stocks = list(
            cls.objects.filter(stock_name=stock_name).values('date', 'open_price', 'highest_price', 'lowest_price',
                                                             'close_price', 'volume'))
        if not stocks:
            cls.get_stock_info(stock_name)
            stocks = list(
                cls.objects.filter(stock_name=stock_name).values('date', 'open_price', 'highest_price', 'lowest_price',
                                                                 'close_price', 'volume'))
        return stocks
    
class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stocks = models.ManyToManyField(Stock)

users/models.py
from django.db import models

# Create your models here.

backend/forms.py
from django import forms
from .models import Watchlist

class AddStockForm(forms.Form):
    stock = forms.CharField(max_length=20)

class WatchlistForm(forms.ModelForm):
    class Meta:
        model = Watchlist
        fields = ['stocks']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self):
        user = User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'],
                                        password=self.cleaned_data['password1'])
        user.save()
        return user

backend/views.py
from django import forms
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView
from django.views.generic.edit import FormView, UpdateView
from backend.forms import WatchlistForm
from backend.models import Stock, Watchlist


class StockNameForm(forms.Form):
    stock_name = forms.CharField(max_length=20)


class DashboardView(TemplateView):
    template_name = 'stocks/dashboard.html'

    def get(self, request, *args, **kwargs):
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            stock_name = kwargs.get('stock_name')
            data = Stock.get_data(stock_name)
            return JsonResponse(data, safe=False)
        else:
            return super().get(request, *args, **kwargs)


class StockGraphView(FormView):
    template_name = 'stocks/dashboard.html'
    form_class = StockNameForm

    def get(self, request, *args, **kwargs):
        stock_name = request.GET.get('stock_name')

        return redirect('dashboard', stock_name=stock_name)


class HomePageView(TemplateView):
    template_name = 'home/home.html'


class WatchlistView(UpdateView):
    model = Watchlist
    form_class = WatchlistForm
    template_name = 'stocks/watchlist.html'
    success_url = reverse_lazy('watchlist')  # replace with your success url

    def get_object(self, queryset=None):
        return Watchlist.objects.get_or_create(user=self.request.user)[0]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        watchlist = self.get_object()
        context['stocks'] = [(stock, stock.get_most_recent_data()) for stock in watchlist.stocks.all()]
        return context

    def post(self, request, *args, **kwargs):
        action = request.POST.get('action')
        stock_name = request.POST.get('stock_name').strip()  # Remove leading and trailing whitespaces
        print(f"stock_name: {stock_name}")  # Print the stock_name to the console
        stock = get_object_or_404(Stock, stock_name__iexact=stock_name)
        watchlist = self.get_object()

        if action == 'add':
            watchlist.stocks.add(stock)
        elif action == 'remove':
            watchlist.stocks.remove(stock)

        return HttpResponseRedirect(reverse('watchlist'))

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegistrationForm
from django.contrib.auth import logout


def register_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to login!')
            return redirect('users:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('users:login')
    return render(request, 'users/logout.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>Stock Market Application - {{ title }}</title>
    {% else %}
        <title>Stock Market Application</title>
    {% endif %}
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href={% static 'css/styles.css' %}>
</head>
<body>

{% include 'navbar.html' %}


{% block content %}

{% endblock %}


<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"
></script>

<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</body>
</html>

templates/home/home.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% load static %}
{% block content %}
    <header id="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-5 offset-md-1 py-5 text-center text-md-start">
                    <h1 class="header-title">Stock Market <br> Application</h1>
                    <h5 class="header-subtitle">Made by Oltean Robert</h5>
                    <blockquote class="header-blockquote">
                        "The Stock Market is filled with individuals
                        who <br> know the price of everything, but the
                        value of nothing."
                        <br>
                        <cite class="header-quote-author">- Phillip Fisher</cite>
                    </blockquote>
                    <a href="#features" class="button button-left">How does it work?</a>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'users:register' %}" class="button button-right">Get Started</a>
                    {% endif %}
                </div>
                <div class="col-md-5 py-5">
                    <img class="header-image img-fluid" src="{% static 'images/image.jpg' %}" alt="Stock Market Image">
                </div>
            </div>
        </div>
    </header>

    <section id="features" class="features">
        <div class="container-fluid">
            <h2 class="text-center">Most Important Features</h2>
            <div class="row">
                <div class="col-12 col-md-6 col-lg-4 py-2 h-auto">
                    <div class="card text-center">
                        <div class="card-header icon-container"><i class="fa fa-money"></i></div>
                        <div class="card-body">
                            <h5 class="card-title text-uppercase">Stock Market Data</h5>
                            <p class="card-text"> Providing real-time data from the stock market,
                                ensuring you have the most up-to-date information at your fingertips. You can track your
                                favorite stocks, view detailed company profiles, and analyze market trends all in one
                                place. We also offer historical data analysis, allowing you to study market patterns
                                over time and make informed investment decisions.</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4 py-2 h-auto">
                    <div class="card text-center">
                        <div class="card-header icon-container">
                            <i class="fa fa-bar-chart-o"></i>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-uppercase">Market Analysis</h5>
                            <p class="card-text"> Offering comprehensive market analysis tools that help
                                you understand the current market trends. With in-depth charts and statistical data,
                                you can easily analyze the performance of various stocks. Our tools also allow you to
                                compare different stocks and sectors, helping you make informed investment decisions.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4 py-2 h-auto">
                    <div class="card text-center">
                        <div class="card-header icon-container"><i class="fa fa-bitcoin"></i></div>
                        <div class="card-body">
                            <h5 class="card-title text-uppercase">Stock Market Prediction</h5>
                            <p class="card-text">Advanced stock market prediction tools. Using
                                machine learning algorithms and historical data, we provide predictive insights to help
                                you anticipate market movements and make strategic investment decisions. These
                                prediction can identify potential investment opportunities and risks, giving you a
                                competitive edge in the market.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="testimonials" class="testimonials">
        <div class="container-fluid">
            <h2 class="text-center">Testimonials</h2>
            <div class="row">
                <div class="col-md-4">
                    <blockquote class="card-text"> Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Adipisci
                        architecto blanditiis
                        consequuntur
                        ducimus ea eligendi fuga id inventore ipsam labore nobis odio, quaerat quasi
                        quisquam,
                        recusandae sequi
                        temporibus unde voluptatum! - User A
                    </blockquote>
                </div>
                <div class="col-md-4">
                    <blockquote class="card-text"> Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Adipisci
                        architecto blanditiis
                        consequuntur
                        ducimus ea eligendi fuga id inventore ipsam labore nobis odio, quaerat quasi
                        quisquam,
                        recusandae sequi
                        temporibus unde voluptatum! - User A
                    </blockquote>
                </div>
                <div class="col-md-4">
                    <blockquote class="card-text"> Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Adipisci
                        architecto blanditiis
                        consequuntur
                        ducimus ea eligendi fuga id inventore ipsam labore nobis odio, quaerat quasi
                        quisquam,
                        recusandae sequi
                        temporibus unde voluptatum! - User A
                    </blockquote>

                </div>
            </div>
        </div>
    </section>

    <footer id="footer" class="footer">
        <div class="container-fluid">
            <div class="row footer-list">
                <div class="col-12 col-md-6 col-lg-6 py-2 h-auto">
                    <a href="https://www.linkedin.com/in/robert-oltean-0888b9251/?originalSubdomain=ro"
                       class="fa fa-linkedin" target="_blank"> Linkedin</a>
                </div>
                <div class="col-12 col-md-6 col-lg-6 py-2 h-auto"><a href="https://github.com/RobertOltean314"
                                                                     class="fa fa-github" target="_blank"> Github</a>
                </div>
                <div class="col-12 col-md-6 col-lg-6 py-2 h-auto"><a href="https://robertoltean.ro/"
                                                                     class="fa fa-coffee" target="_blank"> Personal
                    Website</a></div>
                <div class="col-12 col-md-6 col-lg-6 py-2 h-auto">
                    <a class="fa" href="#">olteanrobertadrian314@gmail.com</a>
                </div>
                <div class="col-12 col-md-12 col-lg-12 py-2 h-auto"><p>© 2024 Oltean Robert. All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand">Stock Market Application</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            {% if user.is_authenticated %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://csac.ulbsibiu.ro/">CSAC</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://scanstart.ro/">ScanStart</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="https://graffino.com/">Graffino</a>
                    </li>
                </ul>

                <ul class="navbar-nav mb-2 mb-lg-0 align-items-center">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <span class="nav-link active">Welcome, {{ user.username }}!</span>
                    </li>
                    <form class="d-flex align-items-center" role="search" action="{% url 'stock_graph' %}" method="GET">
                        <input class="form-control me-2 search-form" type="search" placeholder="Search"
                               aria-label="Search"
                               name="stock_name">
                        <button class="btn btn-success h-75" type="submit">Search</button>
                    </form>
                </ul>

            {% else %}

                <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-disabled="true">Markets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-disabled="true">Crypto</a>
                    </li>
                </ul>


                <ul class="navbar-nav mb-2 mb-lg-0 align-items-center">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:register' %}">Register</a>
                    </li>
                </ul>

            {% endif %}
        </div>
    </div>
</nav>

templates/stocks/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <button id="candlestick-button" class="button button-right">Candle Sticks Chart</button>
    <button id="timeseries-button" class="button button-right">Timeseries</button>
    <button id="ohlc-button" class="button button-right">OHLC</button>
    <button id="volume-button" class="button button-right">Volume</button>

    <!-- Add to Watchlist button -->
    <form method="post" action="{% url 'watchlist' %}">
        {% csrf_token %}
        <input type="hidden" name="action" value="add">
        <input type="hidden" name="stock_name" value="{{ stock.stock_name }}">
        <button type="submit" class="button button-right">Add to Watchlist</button>
    </form>

    <div id="graph-wrapper">
        <div id="graph-container"></div>
    </div>
{% endblock %}

templates/stocks/watchlist.html
{% extends 'base.html' %}

{% block content %}
    <table>
        {% for stock, data in stocks %}
            <tr>
                <td>{{ stock.stock_name }}</td>
                <td>{{ data.close_price }}</td>
                <td>
                    <form method="post" action="{% url 'watchlist' %}">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="remove">
                        <input type="hidden" name="stock_name" value="{{ stock.stock_name }}">
                        <button type="submit">Remove from Watchlist</button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">Your watchlist is currently empty. Use the form below to add a stock to your
                    watchlist.
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="container-fluid login-container text-center">
        <div class="row">
            <div class="col-md-4 offset-md-4 py-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Log in</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success">Login</button>
                            <a href="{% url 'users:register' %}" class="btn btn-light">Register</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock title %}

{% block content %}
    <div class="container-fluid custom-form">
        <div class="row">
            <div class="col-md-10 offset-md-4 text-center">
                <h2>Are you sure you want to log out?</h2>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Logout</button>
                    <a class="btn btn-secondary ml-2" href="{% url 'home' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
    <div class="container-fluid text-left custom-form">
        <div class="row">
            <div class="col-md-6 offset-md-3 py-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Register</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="mb-3">{{ form.username }}</div>
                            <small class="help-text">Required. 150 characters or fewer. Letters, digits and @/./+/-/_
                                only.</small>
                            <div class="mb-3">{{ form.email }}</div>
                            <div class="mb-3">{{ form.password1 }}</div>
                            <div class="mb-3">{{ form.password2 }}</div>
                            <small>
                                <ul>
                                    <li>Your password can't be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can't be a commonly used password.</li>
                                    <li>Your password can't be entirely numeric.</li>
                                </ul>
                            </small>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success">Register</button>
                            <a class="btn btn-light" href="{% url 'users:login' %}">Already have an account?</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}